name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  build-linux:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: fugu
        environment-file: fugu_conda_environment.yml
        auto-activate-base: false
    - name: conda debug
      run: |
        conda info
        conda list
    - name: install?
      run: |
        conda activate fugu
        conda develop .
    - name: Run tests
      run: |
        python3 examples/fugu_test.py