name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  build-linux:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: debug
      run: |
        pwd
        env
        ls -la ~
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: fugu
        environment-file: fugu_conda_environment.yml
        auto-activate-base: false
    - name: conda debug
      run: |
        conda info
        conda list
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env create -f fugu_conda_environment.yml
    - name: Install dependencies
      run: |
        conda init
    - name: Install dependencies
      run: |
        source ~/.bash_profile
        conda activate fugu