name: Fugu integration tests

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

jobs:
  python3.9:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: install deps
      run: |
        pip install -e .
    - name: Run tests with pytest
      run: |
        pytest
  python3.8:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: install deps
      run: |
        pip install -e .
    - name: Run tests with pytest
      run: |
        pytest