name: Python Package using Conda

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: install deps
      run: |
        python3 setup.py install
    - name: Run tests with pytest
      run: |
        pytest