name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  build-linux:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: install?
      run: |
        python3 setup.py install
        pip install -e .[examples]
    - name: Run tests
      run: |
        pytest